### PR TITLE
Add the ability to specify the parity host

### PR DESCRIPTION
**Pull request by SeekTheError**
Wrote this PR so I could use cobalt as a full-blown deployer programmatically.

### CODE REVIEW

**Comment by mirek** [comment]
You can use it already by providing `Object` as `provider`:

```
const Web3 = require('web3')
const makeWeb3 = require('@appliedblockchain/cobalt/make-web3')
const web3 = makeWeb3({
  provider: new Web3.providers.WebsocketProvider('ws://localhost:8546')
})
```

**Comment by mirek** [comment]
But yes, it should be smart/convenient to recognize `ws://`, `wss://`, `http://`, `https://`, `ipc://` (`file:`?)...

**Comment by SeekTheError** [comment]
@mirek Didn't realize you could pass a provider object...
Anyway I added support for ipc:// urls so I guess it's good enough now? Just let me know.

**Comment by mirek** [comment]
I think we shouldn't introduce new "host" attribute, just use `provider` for those values - if it's string then check if it's:
if it's string:
`ganache` -> start ganache
`^wss?` -> ws provider
`^https?` -> http provider
otherwise pass it as is to allow for setting up provider somewhere else.

`parity` case should be removed.

If you do it we can merge otherwise I should have some time soon to look at it.

**Comment by SeekTheError** [comment]
@mirek Done, I left a special case for ipc since the autodetect fails for ipc:// like urls

**Comment by mirek** [comment]
Thanks, feel free to do:
```
npm version minor
git push
git push --tags
```

**Pull request merged**
